[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "glin-sdk"
version = "0.1.0"
description = "Official Python SDK for GLIN AI Training Network"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
    {name = "GLIN AI", email = "dev@glin.ai"}
]
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

dependencies = [
    "substrate-interface>=1.7.0",
    "scalecodec>=1.2.0",
    "requests>=2.31.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.7.0",
    "mypy>=1.5.0",
]

[project.urls]
Homepage = "https://glin.ai"
Documentation = "https://docs.glin.ai/sdk/python"
Repository = "https://github.com/glin-ai/glin-sdk"
"Bug Tracker" = "https://github.com/glin-ai/glin-sdk/issues"
