[package]
name = "glin-sdk"
version = "0.1.0"
edition = "2021"
authors = ["GLIN AI <dev@glin.ai>"]
description = "Official Rust SDK for GLIN AI Training Network"
license = "Apache-2.0"
repository = "https://github.com/glin-ai/glin-sdk"
documentation = "https://docs.rs/glin-sdk"
keywords = ["blockchain", "substrate", "polkadot", "web3", "glin"]
categories = ["cryptography::cryptocurrencies", "api-bindings"]

[dependencies]
# Substrate/Polkadot
subxt = "0.34"
sp-core = "34"
sp-keyring = "39"

# Async runtime
tokio = { version = "1.35", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Codec
parity-scale-codec = { version = "3.6", features = ["derive"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Crypto
hex = "0.4"

# Time
chrono = "0.4"

[dev-dependencies]
tokio-test = "0.4"

[lib]
name = "glin_sdk"
path = "src/lib.rs"
